@startuml

skinparam nodesep 1
left to right direction
package "Group" {
   actor user
   [Browser]
}

package "HTTP-Server" {
package "Interface" {
    [graphical (HTML, CSS, Javascript)               ] as GUIComponent
    [program-based (RestController Spring Boot]
}

node "Java Application" {
    [File Converter               ]
    [RequirementProcessing]
    [AssuranceMapper         ]
    [RessourceChecker]
    [Traverse Algorithm]
}


}

node "MySQL Server" {
database "MySQL" {
  folder "Schema" {
    file assurance_full_object
    file assurance_full_object_seq
  }

}
}


user --> [Browser]
[Browser] --(  "Interface" : API
"Interface" )--( "Java Application"
"Java Application" )--( "MySQL Server"

@enduml