@startuml

skinparam nodesep 1
left to right direction
package "Group" {
   actor user
   [Application]
}

package "Server" {
package "Interface" {
    [graphical          ] as GUIComponent
    [program-based]
}

node "Software Application" {
    [RequirementProcessing]
    [AssuranceMapper         ]
    [RessourceChecker]
    [Traverse Algorithm]
}


}

node "Database Server" {
database "DBMS" {
  folder "Schema" {
    file assurance_full_object
    file assurance_full_object_seq
  }

}
}


user --> [Application]
[Application] --(  "Interface" : API
"Interface" )--( "Software Application"
"Software Application" )--( "Database Server"

@enduml